export interface Integration {
  id: string;
  name: string;
  icon: string;
  description: string;
  instructions: string[];
}

export const integrations: Integration[] = [
  {
    id: "wordpress",
    name: "WordPress",
    icon: "📝",
    description: "Embed your chatbot in your WordPress site",
    instructions: [
      "Copy the embed code above",
      "Go to WordPress post or page editor",
      "Add a new Custom HTML block",
      "Paste the embed code",
      "Save/Update your post or page",
      "Done! Your chatbot will appear on your site",
    ],
  },
  {
    id: "shopify",
    name: "Shopify",
    icon: "🛒",
    description: "Add chatbot to your Shopify store",
    instructions: [
      "Copy the embed code above",
      "Go to your Shopify admin → Online Store → Themes",
      "Click 'Actions' → 'Edit code'",
      "Open 'theme.liquid' file",
      "Paste the embed code before the closing </body> tag",
      "Save the file and refresh your store",
    ],
  },
  {
    id: "wix",
    name: "Wix",
    icon: "🌐",
    description: "Integrate chatbot into your Wix website",
    instructions: [
      "Copy the embed code above",
      "Go to your Wix site editor",
      "Click the '+' button to add an element",
      "Search for 'HTML' and add the 'Custom Code' element",
      "Paste the embed code in the HTML field",
      "Save and publish your site",
    ],
  },
  {
    id: "squarespace",
    name: "Squarespace",
    icon: "⬜",
    description: "Add chatbot to your Squarespace site",
    instructions: [
      "Copy the embed code above",
      "Go to your Squarespace site editor",
      "Click 'Settings' → 'Advanced' → 'Code Injection'",
      "Paste the embed code in the 'Footer' section",
      "Save your changes",
      "Your chatbot will appear on all pages",
    ],
  },
  {
    id: "godaddy",
    name: "GoDaddy",
    icon: "🏠",
    description: "Embed chatbot in your GoDaddy website",
    instructions: [
      "Copy the embed code above",
      "Go to your GoDaddy Website Builder",
      "Click 'Edit Site'",
      "Add a new 'HTML' element to your page",
      "Paste the embed code in the HTML field",
      "Save and publish your site",
    ],
  },
  {
    id: "google-sites",
    name: "Google Sites",
    icon: "🔍",
    description: "Add chatbot to your Google Sites",
    instructions: [
      "Copy the embed code above",
      "Go to your Google Sites editor",
      "Click 'Insert' → 'Embed'",
      "Paste the embed code in the embed field",
      "Adjust size and position as needed",
      "Save your site",
    ],
  },
  {
    id: "joomla",
    name: "Joomla",
    icon: "🌍",
    description: "Integrate chatbot into Joomla",
    instructions: [
      "Copy the embed code above",
      "Go to your Joomla admin panel",
      "Navigate to Extensions → Plugins",
      "Search for 'Custom HTML' plugin and enable it",
      "Create a new article or module with the embed code",
      "Publish and position on your site",
    ],
  },
  {
    id: "drupal",
    name: "Drupal",
    icon: "🐘",
    description: "Add chatbot to your Drupal site",
    instructions: [
      "Copy the embed code above",
      "Go to your Drupal admin panel",
      "Navigate to Structure → Blocks",
      "Create a new custom block",
      "Paste the embed code in the body field",
      "Place the block where you want the chatbot",
    ],
  },
  {
    id: "bigcommerce",
    name: "BigCommerce",
    icon: "🏪",
    description: "Integrate chatbot into BigCommerce",
    instructions: [
      "Copy the embed code above",
      "Go to your BigCommerce admin → Store Setup → Scripts",
      "Click 'Create a Script'",
      "Set location to 'Footer'",
      "Paste the embed code in the script field",
      "Save and activate the script",
    ],
  },
  {
    id: "weebly",
    name: "Weebly",
    icon: "🔧",
    description: "Add chatbot to your Weebly site",
    instructions: [
      "Copy the embed code above",
      "Go to your Weebly site editor",
      "Click the '+' button to add an element",
      "Search for 'Embed Code' and add it",
      "Paste the embed code in the field",
      "Save and publish your site",
    ],
  },
  {
    id: "unbounce",
    name: "Unbounce",
    icon: "📊",
    description: "Integrate chatbot into Unbounce landing pages",
    instructions: [
      "Copy the embed code above",
      "Go to your Unbounce page builder",
      "Click 'Add Element' → 'HTML'",
      "Paste the embed code in the HTML field",
      "Position the element where you want the chatbot",
      "Save and publish your page",
    ],
  },
  {
    id: "framer",
    name: "Framer",
    icon: "🎨",
    description: "Add chatbot to your Framer site",
    instructions: [
      "Copy the embed code above",
      "Go to your Framer project",
      "Click 'Add' → 'Embed'",
      "Paste the embed code in the embed field",
      "Adjust size and position as needed",
      "Publish your site",
    ],
  },
  {
    id: "duda",
    name: "Duda",
    icon: "🏗️",
    description: "Integrate chatbot into Duda websites",
    instructions: [
      "Copy the embed code above",
      "Go to your Duda site editor",
      "Click 'Add Element' → 'HTML'",
      "Paste the embed code in the HTML field",
      "Position the element where you want the chatbot",
      "Save and publish your site",
    ],
  },
  {
    id: "ghost",
    name: "Ghost",
    icon: "👻",
    description: "Add chatbot to your Ghost blog",
    instructions: [
      "Copy the embed code above",
      "Go to your Ghost admin → Code Injection",
      "Paste the embed code in the 'Site Footer' section",
      "Save your changes",
      "Your chatbot will appear on all pages",
    ],
  },
  {
    id: "blogger",
    name: "Blogger",
    icon: "📝",
    description: "Integrate chatbot into Blogger",
    instructions: [
      "Copy the embed code above",
      "Go to your Blogger dashboard",
      "Click 'Theme' → 'Edit HTML'",
      "Find the closing </body> tag",
      "Paste the embed code before the </body> tag",
      "Save your theme",
    ],
  },
  {
    id: "tumblr",
    name: "Tumblr",
    icon: "💭",
    description: "Add chatbot to your Tumblr blog",
    instructions: [
      "Copy the embed code above",
      "Go to your Tumblr dashboard",
      "Click 'Customize' → 'Edit HTML'",
      "Find the closing </body> tag",
      "Paste the embed code before the </body> tag",
      "Save your changes",
    ],
  },
  {
    id: "yola",
    name: "Yola",
    icon: "🌅",
    description: "Integrate chatbot into Yola sites",
    instructions: [
      "Copy the embed code above",
      "Go to your Yola site editor",
      "Click 'Add' → 'Widgets' → 'HTML'",
      "Paste the embed code in the HTML field",
      "Position the widget where you want the chatbot",
      "Save and publish your site",
    ],
  },
  {
    id: "cargo",
    name: "Cargo",
    icon: "📦",
    description: "Add chatbot to your Cargo site",
    instructions: [
      "Copy the embed code above",
      "Go to your Cargo site editor",
      "Click 'Add Element' → 'Code'",
      "Paste the embed code in the code field",
      "Position the element where you want the chatbot",
      "Save and publish your site",
    ],
  },
  {
    id: "piwigo",
    name: "Piwigo",
    icon: "📸",
    description: "Integrate chatbot into Piwigo gallery",
    instructions: [
      "Copy the embed code above",
      "Go to your Piwigo admin panel",
      "Navigate to Configuration → Themes",
      "Edit your current theme's template",
      "Paste the embed code in the footer or header",
      "Save your changes",
    ],
  },
  {
    id: "livejournal",
    name: "LiveJournal",
    icon: "📖",
    description: "Add chatbot to your LiveJournal blog",
    instructions: [
      "Copy the embed code above",
      "Go to your LiveJournal dashboard",
      "Click 'Customize' → 'Journal Style'",
      "Click 'Edit Journal Style'",
      "Paste the embed code in the custom HTML section",
      "Save your style",
    ],
  },
  {
    id: "jigsy",
    name: "Jigsy",
    icon: "🧩",
    description: "Integrate chatbot into Jigsy sites",
    instructions: [
      "Copy the embed code above",
      "Go to your Jigsy site editor",
      "Click 'Add' → 'HTML'",
      "Paste the embed code in the HTML field",
      "Position the element where you want the chatbot",
      "Save and publish your site",
    ],
  },
  {
    id: "im-creator",
    name: "IM Creator",
    icon: "🎯",
    description: "Add chatbot to your IM Creator site",
    instructions: [
      "Copy the embed code above",
      "Go to your IM Creator site editor",
      "Click 'Add' → 'HTML'",
      "Paste the embed code in the HTML field",
      "Position the element where you want the chatbot",
      "Save and publish your site",
    ],
  },
];
